### PR TITLE
Introduce guide link and enhance extensions actions

### LINKED ISSUE #132: Improve Copy Maven command experience
This feature is not obvious enough.

### LINKED ISSUE #258: Add link to guide from list of extensions
**Description**
(Describe the feature here.)

On the code.quarkus.io website, when you are picking among extensions. Then all you have today as details are a short name, and a tiny summary. 

It would be nice if there was a link somewhere (maybe a book icon before the copy to clipboard icon, on the right hand side), you could click that opens a new browser tab, and goes to the guide of the extension (if a guide exists). Where you can read more details about what it does etc.

### PR DESCRIPTION
**Pull request by ia3andy**
Fixes #258, Fixes #132

@fbricon @jeffmaury @xorye, you will now have the `guide` link (optional) available in the extension list.

### CODE REVIEW

**Comment by ia3andy** [comment]
image

**Comment by ia3andy** [comment]
@gsmet @emmanuelbernard @maxandersen this one is really cool :)

**Comment by gsmet** [comment]
+1 looks cool.

**Comment by maxandersen** [comment]
very nice - one improvement could reduce the menu by having it use the chosen build tool and have one "copy add-extension command"

**Comment by emmanuelbernard** [comment]
> very nice - one improvement could reduce the menu by having it use the chosen build tool and have one "copy add-extension command"

Not 100% sure
When you update a project, you don;t naturally change the tool int he dropdown menu before scanning for extensions.

**Comment by maxandersen** [comment]
> Not 100% sure
> When you update a project, you don;t naturally change the tool int he dropdown menu before scanning for extensions.

true - even more reason to get a cli that can just do "the right thing" i.e. "quarkus add-extension panache" no matter what project type you are in :)

**Pull request merged**
