### PR TITLE
updated gradle to 6.3 (supporting java 14)

### PR DESCRIPTION
**Pull request by SR-Lut3t1um**

### CODE REVIEW

**Comment by gastaldi** [comment]
No changes in the wrapper scripts? JARs?

**Comment by gastaldi** [comment]
Ah I see the JAR changes are here, cool

**Comment by gsmet** [comment]
We need to decide if it's something we want for 1.3 or not?

**Comment by gastaldi** [comment]
I think this is important to get early feedback on JDK 14 but not critical, so I'd wait for 1.4

**Comment by gsmet** [comment]
Totally agree, I was checking every day to get my JDK 14 CI PR green.

**Comment by ia3andy** [comment]
Ok, @gsmet @gastaldi I let you merge this or put it on hold.

**Pull request merged**
