### PR TITLE
Feature/#445 - "Open in IDEA" button in push to GitHub modal 

### PR DESCRIPTION
**Pull request by RubensKj**
#445 

Adding "Open in IDEA" button in push to GitHub modal, and adding modal to show the user that the IDEA is opening or it's not supported

### CODE REVIEW

**Comment by ia3andy** [comment]
That looks promising, I will have a look on monday ;-)

**Comment by ia3andy** [comment]
Hey @RubensKj, 

Thanks again for this PR :)

I think we can make the experience a bit simpler without the need of an extra modal by showing the `Open in IDEA` button only when it's supported and the project has been pushed to GitHub.

What do you think?

Cheers,

**Comment by RubensKj** [comment]
Sure!! I will do the changes when I got some time. :)

**Comment by RubensKj** [comment]
One question! In order to get if protocol is supported, the application needs to ask for user if he wants to open the app (checkProtocolCheck does that), is there a problem? Because the button will have to appear everytime the user push to github, but when he clicked it the button should disappear if not supported? For me, I don't think 
 it should appear this "modal" from browser in order to get if is supported or not, it should do internally. 
 
 Do you have an idea about that?

Application needs to open something like this, but not for Zoom, but for Intellij
image

**Comment by ia3andy** [comment]
@RubensKj ahh yeah that would be a problem! Is there no way to avoid it? The idea would be only show the button for people which installed the IDEA plugin and not bother at all the others.

**Comment by RubensKj** [comment]
Ok thanks! I will try to find a solution to avoid this to happen.

**Comment by RubensKj** [comment]
I am very busy with somethings.. I'll work on this on the weekend ok??

**Comment by RubensKj** [comment]
Hello @ia3andy, hope you're well!

Check my status:
I removed the modals and restore to the basic way that the button just appear only if is supported, however, this way I continue with the problem that the `Application is trying to open...`, and I looked a lot of things and I got running out of options about it, I tried to create an hidden iframe, this didn't work too. Tried to pass some other params in `customProtocolCheck` in order to see what happen.. Nothing more than expected, not work too.

I started looking the code from the `Jetbrains Browser Extension`, It appear that this Extension integrates with my Toolbox locally, and with that they know which app that I've installed (Example: Intelllij, WebStorm...). I'll need to have a close look on that file

https://github.com/JetBrains/toolbox-browser-extension/blob/76899362ece740a6f74ea703465b92129128f86d/github.js#L1

So I'd like to know, would you have something in mind that could help me??

**Comment by ia3andy** [comment]
Hey @RubensKj,

Thank you for investigating this deeply!!!

TBH I am not a fan of either making the "Open in IDEA" button for everyone (with/without the plugin installed) and even less having a notification to authorize access for everyone also.

So I guess if we can't find another option, it's a dead end.

I let you decide if you want to let it this way or continue looking for alternative...

What do you think of that one: https://github.com/quarkusio/code.quarkus.io/issues/457

Cheers!

**Comment by RubensKj** [comment]
Hey @ia3andy,  

I think it's a dead end 😟...

I checked the toolbox-browser-extension and I also discovered that the Toolbox gives me an error in case I don't have the application installed on my computer.

image

Sorry about that. The only way is to stay this way... But it's not the way we want it

However, do you like me to close this PR??

**Comment by RubensKj** [comment]
I looked the #457, and I think that's awesome!! 😁

I'm very busy right now with work and university stuff. However, I'll have a look on it, maybe in the next week. That feature it will be very cool to implemented

**Pull request closed without merging**
