### PR TITLE
Change Analytics events proposition

### LINKED ISSUE #238: BuildTool analytics event is not sent

### PR DESCRIPTION
**Pull request by ia3andy**
Fixes #238 

CC: @emmanuelbernard 

This would totally change the current events on GA, the benefits are:
- easier to understand without doc
- more flexible for future events

Could you please be really critical on this so we try not to change them again..

PS: I would understand if you feel we can't change..

# Analytics events
## How popular an extension is in the Code Quarkus app?

The category gives an overall overview of the popularity of an extension, then you can deep dive to particular actions related to extension 

| Category | Action | Label | Description |
| --- | --- | --- | --- |
| Extension | Used | *Extension ID* | This extension has been used in a project |
| Extension | Copy the command to add it with Maven | *Extension ID* | ... |
| Extension | Copy the command to add it with Gradle | *Extension ID* | ... |
| Extension | Copy GAV | *Extension ID* | ... |
| Extension | Click on "Open Extension Guide" link | *Extension ID* | ... |
| Extension | Display in search top 5 results | *Extension ID* | ... |

## What's the preferred way to get the application? / What is the content of generated applications?			

Some custom dimensions are available for those events:
- Extensions: sorted list of selected extension separated by comma
- Build Tool: the selected build tool
- Extension Quantity: the quantity of selected extensions
- Quarkus Version: The Quarkus version

| Category | Action | Label | Description |
| --- | --- | --- | --- |
| App | Download | *clientName* | A application has been generated for the specified client |

## How do users interact with code quarkus?

| Category | Action | Label | Description |
| --- | --- | --- | --- |
| UX | Generate application | Click on "Generate your application" button | ... |
| UX | Post-Generate Popup Action | Start new | ... |
| | | Close | ... |
| | | Go back | ... |
| | | Copy "Dev mode" command | ... |
| | | Click "Download the zip" link | ... |
| | | Click "guides" link | ... |
| | Extension - Unselect | Keyboard/Selection/List | ... |
| | Extension - Select | Keyboard/Selection/List | ... |
| | Extension - Search | *Value* | ... |
| | Blurb | Click on "Missing a feature?" link | ... |
| | | Click on "Found a bug?" link | ... |
| | | Close | ... |

### CODE REVIEW

**Comment by emmanuelbernard** [comment]
I don’t have strong opinions against. But it will make evolutions of numbers harder to track. 
If we do it, I’d argue to do it from 2020-01-01 onwards. 
@maxandersen WDYT?

**Comment by maxandersen** [comment]
Sorry missed the notification. 

I know it's hard to get the events right. On just reading this I'm not grokking what the actual change is but I'll trust you Andy in it being more flexible :)

But as mentioned on mail thread I think better to do this in a clean cut and I would highly suggest to *not* do this just.before Xmas.

**Comment by ia3andy** [comment]
@maxandersen any particular reason why **not** before Xmas?

**Comment by emmanuelbernard** [comment]
@ia3andy are you going to monitor and fix issues

**Comment by maxandersen** [comment]
yes, my point is that we are very interested in seeing how interest changes over xmas break - and thus doing something that sounds like it will affect the various boards monitoring/extracting the data without having them tested before sound like a recipe for loosing data.

Hence I suggest we do this change after the break and optimally make sure we identified anyone who relies on this data to be uptodate so there is no need to send data twice.

**Pull request merged**
