### PR TITLE
Bump to Gradle 6.4.1

### PR DESCRIPTION
**Pull request by gastaldi**
Requires https://github.com/quarkusio/quarkus/pull/9434

### CODE REVIEW

**Comment by ia3andy** [comment]
I added [wip] until Quarkus is up to date with the patch.

**Comment by gastaldi** [comment]
The PR was merged in the quarkus repo

**Comment by gastaldi** [comment]
Oops  accidentally clicked the wrong button :stuck_out_tongue:

**Comment by gastaldi** [comment]
This can be merged anytime, 6.4.1 is compatible with Quarkus 1.4.2.Final too

**Comment by ia3andy** [comment]
@gastaldi so why did you said it required quarkusio/quarkus#9434?

Did you meant it was equivalent?

**Comment by gsmet** [comment]
I merged the 6.4.1 upgrade in Quarkus for CR1 so we're good.

**Comment by gastaldi** [comment]
@ia3andy yeah, for synchronization purposes :+1:

**Pull request merged**
