### PR TITLE
Prepare compatibility with Quarkus 1.9.x

### PR DESCRIPTION
**Pull request by ia3andy**
cc @gsmet @geoand

### CODE REVIEW

**Comment by geoand** [comment]
I have no context about this :)

**Comment by ia3andy** [comment]
> I have no context about this :)

@geoand code.quarkus.io master compatibility with Quarkus master is broken, so I prepared this PR for when we release.

**Comment by geoand** [comment]
So I guess this is something that you and @gsmet can handle :)

**Comment by ia3andy** [comment]
@geoand I tagged you just in case you would release 1.9, instead of using a new PR, you would need to start from that one :)

**Pull request merged**
