### PR TITLE
Add tests for generating Kotlin and Scala projects

### PR DESCRIPTION
**Pull request by aguibert**
Supporting tests for PR https://github.com/quarkusio/quarkus/pull/5311

### CODE REVIEW

**Comment by ia3andy** [comment]
@aguibert beside tests failing 😬(can u have a look?), it's a very good idea to add those! Thanks

**Comment by ia3andy** [comment]
@aguibert maybe it miss the Quarkus fix to pass?

**Comment by aguibert** [comment]
@ia3andy yes, this PR has a pre-req on https://github.com/quarkusio/quarkus/pull/5311

**Comment by ia3andy** [comment]
@aguibert even better then! Nothing better than a failing test before fixing something 😇

**Comment by aguibert** [comment]
hi @ia3andy, the prereq PR over in quarkus is now merged in so this PR should be ready for review and eventual merge now

**Comment by ia3andy** [comment]
@aguibert we need to wait for Quarkus release..

**Pull request merged**
