### PR TITLE
bumped gradle to 6.2

### PR DESCRIPTION
**Pull request by SR-Lut3t1um**

### CODE REVIEW

**Comment by ia3andy** [comment]
@gastaldi could you review this?

**Comment by gastaldi** [comment]
I think you also need to update the other files in the wrapper directory

**Comment by gastaldi** [comment]
Related to https://github.com/quarkusio/quarkus/pull/7252

**Comment by SR-Lut3t1um** [comment]
Allright I did.

**Comment by SR-Lut3t1um** [comment]
This need addition changes, seems like gradle changed how  the wrapper works I'm going to work on that later. Gonne close this PR in the mean time.

**Pull request closed without merging**
