### PR TITLE
bumped gradle to 6.2

### PR DESCRIPTION
**Pull request by SR-Lut3t1um**

### CODE REVIEW

**Comment by ia3andy** [comment]
CI is not passing, there are failing test. @SR-Lut3t1um you should have a look ;-)

**Comment by SR-Lut3t1um** [comment]
Passing now @ia3andy

**Comment by ia3andy** [comment]
I am ok with it if @gastaldi is ok :)

**Comment by gastaldi** [comment]
LGTM No changes in the `gradlew` executable?

**Comment by SR-Lut3t1um** [comment]
Nope no changes, I checked it/ moved the file and git also detected no changes.

**Comment by gastaldi** [comment]
Can you squash your commits into a single one? Thanks!

**Comment by ia3andy** [comment]
Merged

**Comment by ia3andy** [comment]
It's now in production, thanks @SR-Lut3t1um !!

**Pull request merged**
