### PR TITLE
Bump Quarkus and platform versions to 1.0.0.CR2

### PR DESCRIPTION
**Pull request by gsmet**

### CODE REVIEW

**Comment by ia3andy** [comment]
@gsmet does this new version includes @aloubyansky changes to have global platform configuration?

**Comment by ia3andy** [comment]
If it does, it requires a small change in the code..

**Comment by aloubyansky** [comment]
Andy, you should be able to use the static global config again now. And I'll finish the PR that removes the global config soon (hopefully this week, unless something else come up).

**Comment by gsmet** [comment]
Could you be more explicit about which changes you're talking about?

Included changes from Alexey are here: https://github.com/quarkusio/quarkus/pulls?q=is%3Apr+milestone%3A1.0.0.CR2+is%3Aclosed+author%3Aaloubyansky .

**Comment by ia3andy** [comment]
@gsmet I'm currently adding the required changes, no worries, @aloubyansky answered..

**Comment by gsmet** [comment]
BTW, I tested it yesterday and it worked OK so I suppose this change is not mandatory?

Or should I check other things next time?

**Comment by ia3andy** [comment]
@gsmet I've submitted the change, it is really small, it fixes a rare case of concurrency problem (that's why it worked).

**Comment by gsmet** [comment]
@ia3andy I removed your commit for now as it breaks CI. I need to release so I will release without it and then you can play with it and submit another PR.

Thanks.

**Pull request merged**
