### PR TITLE
Bump Quarkus and Platform to 1.1.1.Final

### PR DESCRIPTION
**Pull request by gsmet**

### CODE REVIEW

**Comment by ia3andy** [comment]
@gsmet not need to update the graalvm image? (I need to add it to the upgrade procedure)

**Comment by ia3andy** [comment]
https://github.com/quarkusio/code.quarkus.io/blob/master/src/main/docker/Dockerfile.native.multistage#L2

**Comment by gsmet** [comment]
No. I'm not releasing master, I'm releasing the 1.1 branch.

**Comment by ia3andy** [comment]
@gsmet ok I added it in the doc so at least we check when releasing: https://github.com/quarkusio/code.quarkus.io/commit/e272b40b69647eb7ad2116bec0abface99aabcc1

**Pull request merged**
