### PR TITLE
Show LTS flag on streams

### PR DESCRIPTION
**Pull request by nikolassv**
Solves Issue #1246.

### CODE REVIEW

**Comment by ia3andy** [comment]
@nikolassv thanks! do you have a screenshot?

**Comment by nikolassv** [comment]
Yes, it looks like this:

grafik

**Comment by ia3andy** [comment]
ok my concern is that it might not show well when mixed with recommended and status, so could we try this:
- use fixed column width
- put the Status or LTS next to the version 3.2 - LTS
- Use a star icon for the Recommended (with a title="Recommended")

wdyt?

**Comment by nikolassv** [comment]
Yes, it might not mix well. I will give your recommendation a try, so that we have a screenshot for comparison.

**Comment by nikolassv** [comment]
Ok, I tried several things here. This is a version with the status right behind the version number and a star for the recommended version:

grafik

In my opinion the first column with the version number and the status looks to wide. So I tried a version where I keep the tags in the end and use a star icon for the recommended version. Currently, It would look like this:

grafik

If the current recommended version was a LTS it would look like this:

grafik

Lastly, I tried a version, where I keep the tags at the end but put the status and "recommended" into the same parenthesis if both tags apply to the same version. It would look like this:

grafik

What are your thoughts on this? Do you have a favorite?

**Comment by ia3andy** [comment]
Thanks for this :)

I'll go for if you also like it:

 

But could we keep the fixed width like on the other?

**Comment by nikolassv** [comment]
I prefer that one, too. I implemented it with the fixed column width for the stream id. The "LTS" will only be displayed, if no status is displayed which is the case when the status is `FINAL`.

It looks like this, when the recommended stream is not a LTS:

grafik

And like this when the recommended stream is a LTS:

grafik

**Comment by ia3andy** [comment]
@nikolassv that's looks very nice! Go go go

**Comment by ia3andy** [comment]
did you push this already?

**Comment by nikolassv** [comment]
Yes, it's already in my last commit.

**Review by ia3andy — APPROVED** [review]
Awesome!

**Comment by ia3andy** [comment]
This will be in prod in less than an hour

**Pull request merged**
