### PR TITLE
Button to store current app as default (in local storage) 

### LINKED ISSUE #591: Button to store current app as default (in local storage)
**Description**
I would be nice to have a button to store the current app as default (in local storage).

We could put it in the Generate Menu "Store current app as default":
image

### PR DESCRIPTION
**Pull request by tacsio**
1- Get the project from the local storage in resolveInitialProject():
2- Set the project in local storage when clicking on the button 'Store current app as default'

Override order: Query params > localstorage > default

Fixes #591

### CODE REVIEW

**Review by ia3andy — CHANGES_REQUESTED** [review]
Code looks neat :)
Very good idea to keep the stored state until a new change!

Just a small detail, when downloading a project the button "start a new project" is returning to original default.

Also it might be nice to find a way to go back to original default. Maybe some kind of trash split button on the right of the store button when the storage contains something different than the original default). 
This could be in a different PR.

**Comment by tacsio** [comment]
Great, I'll fix this behavior of the "start new project" button.

About the default button... the ideia of a trash button on the right could be like the trash icon of selected extensions (that shows when hovering over).

Putting the PR to draft state.

**Comment by tacsio** [comment]
> Just a small detail, when downloading a project the button "start a new project" is returning to original default.


Hey @ia3andy , I've fixed the bug when clicking "start a new application" button.

**Review by ia3andy — APPROVED** [review]

**Comment by tacsio** [comment]
My twitter is @tacsio too.

About the feature of the trash button to 'reset' to default project settings, You'll create a new issue for that?

**Pull request merged**
