### PR TITLE
Retry 5 times to see if the repository exists before pushing

### PR DESCRIPTION
**Pull request by ia3andy**

### CODE REVIEW

**Comment by maxandersen** [comment]
What issue is this solving ? Why not just check once - why 5 times is necessary?

**Comment by ia3andy** [comment]
@maxandersen this is a quickfix, the "push to GitHub" currently fails 70% of the times, it seems GitHub api has changed and the repository is not yet fully created when the `create` response is sent.

**Comment by ia3andy** [comment]
FYI locally I went to 1 retry failing and then the content was successfully pushed, so 5 should be a good safety. On top of that when it was failing before this fix, it was creating the repo but stopped before pushing the content..

Also, if you find a better approach you are free to provide a PR :)

**Comment by maxandersen** [comment]
Makes sense. Didn't realize that was the issue based on the commits/description so was confused :) thanks for clarifying.

**Comment by ia3andy** [comment]
Yeah I made this fix late yesterday and should have provided more context.

**Pull request merged**
