### PR TITLE
Fix project for Quarkus 0.24

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #166

### CODE REVIEW

**Comment by geoand** [comment]
OK, let me do that

**Comment by geoand** [comment]
@gastaldi I am getting:

```
TypeError: Cannot read property 'writeFile' of undefined
    at /home/gandrian/projects/redhat/code.quarkus.io/extensions/generate-extensions.ts:66:20
    at step (/home/gandrian/projects/redhat/code.quarkus.io/extensions/generate-extensions.ts:43:23)
    at Object.next (/home/gandrian/projects/redhat/code.quarkus.io/extensions/generate-extensions.ts:24:53)
    at fulfilled (/home/gandrian/projects/redhat/code.quarkus.io/extensions/generate-extensions.ts:15:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
Done in 3.64s.
```

Do you have a quick remedy for this or would you like to perform the update?

**Comment by gastaldi** [comment]
Not sure why that error is happening. I may have a look later

Em Sáb, 12 de out de 2019 09:03, Georgios Andrianakis <
notifications@github.com> escreveu:

**Comment by geoand** [comment]
So should we merge this so @cescoffier can continue with the release?

**Comment by cescoffier** [comment]
Yes, would be great!

**Comment by geoand** [comment]
I don't have the karma to merge, @gastaldi I assume you do?

**Pull request merged**
