### PR TITLE
Improve mobile/tablets layout

### PR DESCRIPTION
**Pull request by ia3andy**
@edewit could you check I didn't break anything 😅

Capture d’écran 2020-01-17 à 10 52 41
Capture d’écran 2020-01-17 à 10 52 32

### CODE REVIEW

**Comment by ia3andy** [comment]
@maxandersen @emmanuelbernard I think you guys were waiting for this too 😅

**Comment by emmanuelbernard** [comment]
test where?

**Comment by ia3andy** [comment]
@emmanuelbernard I'll ping you when it's on staging so you can have a look before going to prod

**Comment by ia3andy** [comment]
@emmanuelbernard ok you can try it there: https://stage.code.quarkus.io/

**Comment by emmanuelbernard** [comment]
Looks good.
I wonder why we limit the description (`...`) in case the screen is really wide though. You literally can read more text when your screen is smaller.

Screenshot 2020-01-17 at 12 18 32
Screenshot 2020-01-17 at 12 18 42

**Comment by ia3andy** [comment]
> I wonder why we limit the description (...) in case the screen is really wide though.

@emmanuelbernard how would you deal with it otherwise? On larger screen we only use one line.

> You literally can read more text when your screen is narrower.

Yes but then the list takes a lot less height thought

**Pull request merged**
